### ISSUE TITLE
The results of the experiment cannot be reproduced.

### ISSUE THREAD

**Issue by junjzhang7** [ycq091044/ManyDG#4]
Excellent work! But, something goes wrong when I try to reproduce your work.

I download the data from SafeDrug and run the python file `python run_drugrec/run_drugrec.py --model baseGAMENet --cuda 0 --N_pat 4233 --epochs 100` for drug recommendation. However, I got `test jaccard: 0.4299, prauc: 0.7025, f1: 0.5925` , and `test jaccard: 0.4272, prauc: 0.6964, f1: 0.5908` for `--model  devGAMENet`.

I am so confused and looking forward to your reply.

**Comment by ycq091044** [comment]
Sure I would like to help. But I have to get back to you in a few weeks. Sorry, I am a bit busy recently. Just keep the issue open.

**Comment by ycq091044** [comment]
@junjzhang7  Hi, sorry for the late reply. Your results are QUITE different from mine. Apparently, you data processing scripts are wrong.

I have two comments here:
1. "I download the data from SafeDrug", by saying this, did you just download the data from SafeDrug repo? The data I provided in SafeDrug Repo is for demo purpose. It only contains 100 records.
2. Please download MIMIC-III dataset and use our provided scripts https://github.com/ycq091044/ManyDG/blob/main/data/drugrec/data_processing.py to process the drug recommendation task.

Let me know what you can get from the complete MIMIC-III dataset.

**Comment by yuliang-liang** [comment]
I have the same problem. I tried using SafeDrug files and ManyDG preprocessing, and the results were not good.

**Comment by ycq091044** [comment]
Please provide the detailed procedures below. 

1. The data I provided in SafeDrug Repo is for demo purpose. It only contains 100 records.
2. Please download MIMIC-III dataset and use our provided scripts https://github.com/ycq091044/ManyDG/blob/main/data/drugrec/data_processing.py to process the drug recommendation task.

**Comment by humphreyhuu** [comment]
Firstly, many thanks for sharing code. I also got similar results. I was literally following the instruction in the markdown file. However, other baselines got similar performance. Is there any modules shown in paper not used in code?
